services:
  - type: web
    name: zoe-xd
    repo: https://github.com/Xirtexe/Zoe.git
    branch: main
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    runtime: docker
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_APP_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION
        sync: false
        required: true
      - key: SUDO
        sync: false
        required: true
      - key: HANDLER
        sync: false
        required: true
      - key: MODE
        sync: false
        required: true

