services:
  - type: web
    name: zoe-xd
    repo: https://github.com/Xirtexe/Zoe.git
    branch: main
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_APP_NAME
        sync: false
      - key: RENDER_API
        sync: false
      - key: SESSION
        sync: false
      - key: SUDO
        sync: false
      - key: HANDLER
        sync: false
      - key: MODE
        sync: false
